version: "3.9"

services:
  server:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SELECT 1"]
      interval: 5s
      timeout: 30s
      retries: 10

volumes:
  my-db:
